// Servidor principal de la aplicación DIAN.
require('dotenv').config(); const express = require('express'); const cors = require('cors'); const multer = require('multer'); const path = require('path'); const { login, protect } = require('./auth'); const { parseExcel } = require('./excelParser'); const { analyzeExcel } = require('./groq'); const { buildExcel } = require('./excelBuilder');
const { iniciar: iniciarDian, status: estadoDian } = require('./dianAutomation'); const app = express(), upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 20 * 1024 * 1024 } }); app.use(cors()); app.use(express.json({ limit: '2mb' })); app.use(express.static(path.join(__dirname, '..', 'frontend')));
app.post('/api/login', (req,res) => { try { res.json({ token: login(req.body.user, req.body.pass) }); } catch(e) { res.status(401).json({error:e.message}); } });
app.post('/api/parse', protect, upload.single('file'), (req,res) => { try { if (!req.file || !/\.(xlsx|xls)$/i.test(req.file.originalname)) throw new Error('Suba un archivo .xlsx o .xls'); res.json(parseExcel(req.file.buffer)); } catch(e) { res.status(400).json({error:e.message}); } });
app.post('/api/analyze', protect, async (req,res) => { try { res.json(await analyzeExcel(req.body.encabezados, req.body.muestra)); } catch(e) { res.status(502).json({error:e.message}); } });
app.post('/api/dian/start', protect, (req,res) => { if(process.env.VERCEL) return res.status(501).json({error:'La automatización DIAN requiere ejecutar la aplicación localmente.'}); res.json({mensaje:'Automatización iniciada. Completa el acceso manualmente en la ventana DIAN.'}); iniciarDian(req.body.anio || new Date().getFullYear()).catch(()=>{}); }); app.get('/api/dian/status', protect, (_,res) => res.json(estadoDian()));
app.get('/api/dian/file', protect, (req,res) => { try { const f=estadoDian().archivo; if(!f) return res.status(404).json({error:'Aún no hay archivo descargado'}); res.download(f); } catch(e) { res.status(404).json({error:e.message}); } });
app.post('/api/build', protect, (req,res) => { try { const b=buildExcel(req.body.datos, req.body.mapeo, req.body.formato, req.body.observaciones); res.set({ 'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'Content-Disposition':'attachment; filename="exogena_personalizada.xlsx"' }).send(b); } catch(e) { res.status(400).json({error:e.message}); } });
app.get('*', (_,res) => res.sendFile(path.join(__dirname,'..','frontend','index.html')));
if (require.main === module) app.listen(process.env.PORT || 3000, () => console.log(`Aplicación DIAN en http://localhost:${process.env.PORT || 3000}`));
module.exports = app;
